### ISSUE TITLE
Deprecated configuration parameter found: overrideDefaultVerticalSwing

### ISSUE THREAD

**Issue by dsylex** [eibenp/homebridge-gree-airconditioner#28]
**Describe The Bug:**
Gree devices unresponsive to changes from Home App, however they do change states and work remotely via the official Gree app.

**To Reproduce:**

**Expected behavior:**
Responsivity to state changes

**Logs:**

```
[09/04/2025, 12:57:59] [GREE Air Conditioner] [Bedroom AC -- 192.168.1.xx0] Device is bound -> xxxxxx
[09/04/2025, 12:57:59] [GREE Air Conditioner] [Kid1 AC -- 192.168.1.xx2] Device is bound -> xxxxxx
[09/04/2025, 12:57:59] [GREE Air Conditioner] [Living Room AC -- 192.168.1.xx1] Device is bound -> xxxxxx
[09/04/2025, 12:57:59] [GREE Air Conditioner] [Wardrobe AC -- 192.168.1.xx5] Device is bound -> xxxxxx
[09/04/2025, 12:57:59] [GREE Air Conditioner] [Kid2 AC -- 192.168.1.xx4] Device is bound -> xxxxxx
[09/04/2025, 12:57:59] [GREE Air Conditioner] [ManCave AC -- 192.168.1.xx6] Device is bound -> xxxxxx
[09/04/2025, 12:58:58] [GREE Air Conditioner] Deprecated configuration parameter found: overrideDefaultVerticalSwing - Accessory xxxxxx parameter value: 1 -> use modifyVerticalSwingPosition
[09/04/2025, 12:58:58] [GREE Air Conditioner] Deprecated configuration parameter found: overrideDefaultVerticalSwing - Accessory xxxxxx parameter value: 1 -> use modifyVerticalSwingPosition
[09/04/2025, 12:58:58] [GREE Air Conditioner] Deprecated configuration parameter found: overrideDefaultVerticalSwing - Accessory xxxxxx parameter value: 1 -> use modifyVerticalSwingPosition
[09/04/2025, 12:58:58] [GREE Air Conditioner] Deprecated configuration parameter found: overrideDefaultVerticalSwing - Accessory xxxxxx parameter value: 1 -> use modifyVerticalSwingPosition
[09/04/2025, 12:58:58] [GREE Air Conditioner] Deprecated configuration parameter found: overrideDefaultVerticalSwing - Accessory xxxxxx parameter value: 1 -> use modifyVerticalSwingPosition
[09/04/2025, 12:58:58] [GREE Air Conditioner] Deprecated configuration parameter found: overrideDefaultVerticalSwing - Accessory xxxxxx parameter value: 1 -> use modifyVerticalSwingPosition
```

**Plugin Config:**

```
{
    "name": "GREE Air Conditioner",
    "port": 7002,
    "scanInterval": 60,
    "devices": [
        {
            "mac": "xxxxxx",
            "name": "ManCave AC",
            "speedSteps": 5,
            "statusUpdateInterval": 10,
            "sensorOffset": 40,
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "xFanEnabled": true,
            "temperatureSensor": "disabled",
            "overrideDefaultVerticalSwing": 1,
            "defaultVerticalSwing": 2,
            "encryptionVersion": 0
        },
        {
            "mac": "xxxxxx",
            "name": "Kid1 AC",
            "speedSteps": 5,
            "statusUpdateInterval": 10,
            "sensorOffset": 40,
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "xFanEnabled": true,
            "temperatureSensor": "disabled",
            "overrideDefaultVerticalSwing": 1,
            "defaultVerticalSwing": 2,
            "encryptionVersion": 0
        },
        {
            "mac": "xxxxxx",
            "name": "Wardrobe AC",
            "speedSteps": 5,
            "statusUpdateInterval": 10,
            "sensorOffset": 40,
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "xFanEnabled": true,
            "temperatureSensor": "disabled",
            "overrideDefaultVerticalSwing": 1,
            "defaultVerticalSwing": 2,
            "encryptionVersion": 0
        },
        {
            "mac": "xxxxxx",
            "name": "Bedroom AC",
            "speedSteps": 5,
            "statusUpdateInterval": 10,
            "sensorOffset": 40,
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "xFanEnabled": true,
            "temperatureSensor": "disabled",
            "overrideDefaultVerticalSwing": 1,
            "defaultVerticalSwing": 2,
            "encryptionVersion": 0
        },
        {
            "mac": "xxxxxx",
            "name": "Kid2 AC",
            "speedSteps": 5,
            "statusUpdateInterval": 10,
            "sensorOffset": 40,
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "xFanEnabled": true,
            "temperatureSensor": "disabled",
            "overrideDefaultVerticalSwing": 1,
            "defaultVerticalSwing": 2,
            "encryptionVersion": 0
        },
        {
            "mac": "xxxxxx",
            "name": "Living Room AC",
            "speedSteps": 5,
            "statusUpdateInterval": 10,
            "sensorOffset": 40,
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "xFanEnabled": true,
            "temperatureSensor": "disabled",
            "overrideDefaultVerticalSwing": 1,
            "defaultVerticalSwing": 2,
            "encryptionVersion": 0
        }
    ],
    "platform": "GREEAirConditioner"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v2.2.0
* **Homebridge Version**: v1.9.0
* **Node.js Version**: v22.14.0
* **Operating System**: Raspberry Pi OS

**Comment by eibenp** [comment]
First of all: "Deprecated configuration parameter found" is a warning message that you have upgraded the plugin but did not upgrade the configuration settings. Please upgrade the configuration settings by using the graphical configuration tool or manually by following the documentation.

It is documented that sometimes devices may be unresponsive. The reason can be a bug which was fixed in the latest version, but Homebridge caches old state of the device. In this case you have to disable the devices, restart homebridge and re-enable the devices.

If you have already disabled and re-enabled the devices after upgrading both the plugin and the configuration to the latest version, but the problem is still present, please try to restart your device (unplug power and re-connect power after a few minutes).

You have attached the plugin log but it doesn't contain any information regarding the problem. If the above steps do not help, please turn on debug logging and attach detailed debug log to this issue.

**Comment by dsylex** [comment]
> > First of all: "Deprecated configuration parameter found" is a warning message that you have upgraded the plugin but did not upgrade the configuration settings. Please upgrade the configuration settings by using the graphical configuration tool or manually by following the documentation.
> > It is documented that sometimes devices may be unresponsive. The reason can be a bug which was fixed in the latest version, but Homebridge caches old state of the device. In this case you have to disable the devices, restart homebridge and re-enable the devices.
> > If you have already disabled and re-enabled the devices after upgrading both the plugin and the configuration to the latest version, but the problem is still present, please try to restart your device (unplug power and re-connect power after a few minutes).
> > You have attached the plugin log but it doesn't contain any information regarding the problem. If the above steps do not help, please turn on debug logging and attach detailed debug log to this issue.
> 
> Alright, thanks. Changing "modify vertical position" to anything else than current, restarting child bridge, then changing back to "never" solved the trick. It did not specifically mention in the documentation that it had to be changed due to an update, so I'll leave the proper **_solution_** here for future reference.

unfortunately the bug came back after about 30 mins, so I'll try the other steps to resolve and check back soon

**Comment by dsylex** [comment]
debug log attached

[homebridge-gree-ac.log.txt](https://github.com/user-attachments/files/19758254/homebridge-gree-ac.log.txt)

**Comment by eibenp** [comment]
You have a lot of AC units. Are they all independent units (single unit split AC), or you have some multi unit split ACs?
Multi unit ACs share one outdoor unit so all of the indoor units have to set to the same mode. (The outdoor unit can't work in multiple modes at the same time.)
Your AC units are in different modes. Some of them are turned off. Some are heating and some cooling. In the logs I see that Kid1 AC earlier was trying to set to cooling mode, but it did not accept the cooling mode command, and it is still in heating mode. When you try to turn on the unit in heating mode, it refuses the command because it is still waiting a cooling mode response from the unit. I guess that Kid1 AC is a multi unit split AC and cooling mode was refused because other indoor unit was already working in a different mode. The plugin will not accept any power command until the AC unit is turned into cooling mode (by the remote control).
Please confirm if I am on the right way.
I am thinking on a solution but I should know if this is the problem or not.

**Comment by dsylex** [comment]
They are all individual AC’s and all of them have individual internal and external units and work independently from each other. The Kid1 AC and Wardrobe AC are the ones which usually have problem since the last version. They are different from the others in regards to fw version (and even though they are also comfortx or comfort pro (?) models, they are newer version).

**Comment by eibenp** [comment]
OK, then I was on a wrong way.
I am sure that an incomplete switch to cooling mode was preventing Kid1 AC from turning on in heating mode. Unfortunately the logs are missing this cooling event, so I do not know the reason at the moment.
Can you reproduce the problem and describe me the steps how to reproduce it?

**Comment by eibenp** [comment]
@dsylex 

I have published a new beta version (2.2.1-beta.1). You can test if it solves your problem.

**Comment by dsylex** [comment]
Thank you! It seems to be fine on beta version, I’ll test it for a few days and get back to you.

**Comment by dsylex** [comment]
Yes, sorry, I didn’t get back to you. It works stellar and didn’t experience any issues ever since upgrading to the beta version.

**Comment by eibenp** [comment]
Thank You!
I have published the final release of version v2.2.1
